### PR TITLE
LPS-53748 Support for findbugs on plugins and modules

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Can we automate the findbugs installation process? Better to keep it as ignored local libs.

**Comment by shuyangzhou** [comment]
Oops, missed your last commit somehow :)

**Comment by shuyangzhou** [comment]
Ok, there is some problems here.

1) findbugs.home=/usr/lib/findbugs

This is assuming linux env, windows users won't like it. We should make it a local install within the repository. As a matter of fact, we would want to keep the scanning result consistent, so it will be better to always use the auto installed version of findbugs, not using user's local installation, in case the local one is a different version.

2) Avoid copying jar into ant/lib, there should be ways to create a dedicated classpath to run findbugs' task, without messing with ant installation

3) Create an unit to test the findbugs on CI, just as we did for PMD.

Can we make those changes? Thanks!

**Comment by mdelapenya** [comment]
Which project directory should I use to put the findbugs home? I though sdk.dir/tools/findbugs/finbugs-VERSION could be a good choice.

Do you agree?

**Pull request closed without merging**
